export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_START = "AUTH_START";

export const VERIFY_START = "VERIFY_START";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const FORGOTTEN_START = "FORGOTTEN_START";
export const FORGOTTEN_SUCCESS = "FORGOTTEN_SUCCESS";
export const FORGOTTEN_FAIL = "FORGOTTEN_FAIL";

export const PROFILE_EDIT_START = "PROFILE_EDIT_START";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";

export const DELETE_ACCOUNT_START = "DELETE_ACCOUNT_START";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";

export const SEND_PASSWORD_RESET_EMAIL_START = "SEND_PASSWORD_RESET_EMAIL_START";
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = "SEND_PASSWORD_RESET_EMAIL_SUCCESS";
export const SEND_PASSWORD_RESET_EMAIL_FAIL = "SEND_PASSWORD_RESET_EMAIL_FAIL";

export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_FAIL = "ADD_PATIENT_FAIL";
export const ADD_PATIENT_START = "ADD_PATIENT_START";

export const CHANGE_THEME_START = "CHANGE_THEME_START";
export const CHANGE_THEME_FAIL = "CHANGE_THEME_FAIL";
export const CHANGE_THEME_SUCCESS = "CHANGE_THEME_SUCCESS";

export const PROFILE_PHOTO_START = "PROFILE_PHOTO_START";
export const PROFILE_PHOTO_SUCCESS = "PROFILE_PHOTO_SUCCESS";
export const PROFILE_PHOTO_ERROR = "PROFILE_PHOTO_ERROR";

export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const CLEAN_UP = "CLEAN_UP";
